#!/bin/bash

# Usage: gca 'your_full_name' 'your_email'
# Make sure to thank David Dobrynin

function git_change_authorship {
  git filter-branch -f --env-filter "GIT_AUTHOR_NAME=; GIT_AUTHOR_EMAIL=; GIT_COMMITTER_NAME=; GIT_COMMITTER_EMAIL=;"
}

# make `g` behave like `git status` with no args, or `git` with args
g () {
  if [ $# -eq 0 ]
  then
    git status
  else
    git "$@"
  fi
}
__git_complete g _git

#aliases

alias sl="ls"
alias ls="ls -a"
alias irb="pry"
alias be="bundle exec"
alias ber="bundle exec rspec"


alias gi="git init"
alias gaa="git add -A"
alias gcm="git commit -m"
alias gp="git push"
alias gca=git_change_authorship

# For my eternal respect, dare to push your own changes into this repo
